testingisdocumenting/znai

pom.xml
Release perform failed with:
```
[INFO] [ERROR] Repository "comtwosigmaznai-1000" failures
[INFO] [ERROR]   Rule "javadoc-staging" failures
[INFO] [ERROR]     * Missing: no javadoc jar found in folder '/com/twosigma/znai/znai-groovy/0.14'
[INFO] [ERROR]     * Missing: no javadoc jar found in folder '/com/twosigma/znai/znai-testing-tcli/0.14'
```
The change in this PR is the only relevant difference with webtau that I can see.  Unfortunately, I can't see any obvious way to test this without attempting a release 😞
=> add groovydoc

pom.xml
Without this, one needs to go to the Sonatype UI, find the staging repo and press release manually which is a little tedious.
=> set auto release to true

pom.xml
1.4 has an issue whereby the artifact name in the published pom does not match the artifactId in Maven Central.  This causes issues for Gradle and SBT users as both of those tools fail resolution upon encountering such issues.  1.5 fixes this.
=> Upgrade ant-compress

znai-cli/src/main/java/com/twosigma/znai/cli/ZnaiCliApp.java, znai/src/main/java/com/twosigma/znai/website/WebSite.java, znai/src/main/java/com/twosigma/znai/website/markups/MarkdownParsingConfiguration.java, znai/src/main/java/com/twosigma/znai/website/markups/MarkupParsingConfiguration.java, znai/src/main/java/com/twosigma/znai/website/markups/MarkupParsingConfigurations.java, znai/src/main/java/com/twosigma/znai/website/markups/SphinxParsingConfiguration.java, znai/src/main/resources/META-INF/services/com.twosigma.znai.website.markups.MarkupParsingConfiguration, znai/src/test/groovy/com/twosigma/znai/website/markups/MarkupParsingConfigurationsTest.groovy
This change will allow to register additional implementations of `MarkupParsingConfiguration`. It can be used to either support different types of markup languages (i.e. ascii doctor) or provide a different Table Of Contents generation.
=> extensible markup configurations

znai-docs/documentation/snippets/HelloWorld.java, znai-docs/documentation/snippets/java.md, znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaIncludePlugin.java, znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaIncludePluginBase.java, znai-java/src/main/java/com/twosigma/znai/java/parser/JavaCode.java, znai-java/src/main/java/com/twosigma/znai/java/parser/JavaCodeVisitor.java, znai-java/src/test/groovy/com/twosigma/znai/java/extensions/JavaIncludePluginTest.groovy, znai-java/src/test/resources/Simple.java
Add option to list of all the method overloads to help with reference documentation.
```
:include-java: HelloWorld.java {entries: "sampleMethod", signatureOnly: true}
```
```
class HelloWorld {
private int numberOfStudents;
public String sampleMethod(String p1, int p2) {
//...
}
public void sampleMethod(Map<String, Integer> p1, int p2, boolean isActive) {
// overloaded method
}
public void importantAction() {
// TODO important
}
public Data createData() {
// create data
}
}
```
```
public String sampleMethod(String p1, int p2)
public void sampleMethod(Map<String, Integer> p1, int p2, boolean isActive)
```
=> add list all overloads for a specified java method name

pom.xml, znai-core/pom.xml, znai-diagrams/pom.xml
The change also replaced from jaxb-api to jakarta.xml.bind-api, since J2EE packages are not included as part of JDK in JDK11.
=> upgrade jackson from 2.9.9 to 2.10, so databind can be the same version

znai-reactjs/src/doc-elements/table/Table.js, znai/src/main/java/com/twosigma/znai/extensions/api/ApiParametersCsvParser.java, znai/src/main/java/com/twosigma/znai/extensions/table/CsvParser.java
1. We don't have to convert a number to BigDecimal unless znai needs to compute the field. Also ApiParametersCsvParser throws an exception if a field is a number.
For example, when we define a return value, a number can't be an argument.
```api-parameters
0,, on success
```
ApiParametersCsvParser.parseRow(ApiParametersCsvParser.java:55) throws an exception since it tries to cast BigDecimal to String.
2. Another bug fix is that if name has more than one dot, it's not a nested part. We need to handle a name with multiple dots as is.
For example, 
```api-parameters
...,, Variable parameters
```
3. add missing width for a table
=> make all of fields in csv String. 

znai-reactjs/src/doc-elements/DefaultElementsLibrary.js, znai-reactjs/src/doc-elements/Documentation.js, znai-reactjs/src/index.js, znai-reactjs/src/theme/ThemeRegistry.js
Introduce a better way to override a component to render parts of documentation across multiple themes.
=> Override elements through theme registry. expose DocumentationLayout.

znai-core/src/main/java/com/twosigma/znai/parser/MarkupParser.java, znai-core/src/main/java/com/twosigma/znai/parser/commonmark/MarkdownParser.java, znai-core/src/main/java/com/twosigma/znai/structure/DocStructure.java, znai-core/src/test/groovy/com/twosigma/znai/parser/TestDocStructure.groovy, znai-core/src/test/groovy/com/twosigma/znai/parser/TestMarkdownParser.groovy, znai-core/src/test/groovy/com/twosigma/znai/parser/TestMarkupParser.groovy, znai-sphinx/src/main/java/com/twosigma/znai/parser/sphinx/SphinxDocTreeParser.java, znai/src/main/java/com/twosigma/znai/website/WebSite.java, znai/src/main/java/com/twosigma/znai/website/WebSiteDocStructure.java
`TableOfContents` Items has page meta part. To make sure page meta is filled with data, we now parse page meta first for all the pages before attempting to parse each page fully. This is done some plugins that need access to `TableOfContents` have access to page meta parts of each `TocItem`.
Meta only parsing is fast since no plugins will be activated and no search information will be calculated.
=> Expose TableOfContents through DocStructure interface for plugins to access

znai-docs/documentation/custom.html, znai-docs/documentation/extensions.json, znai-docs/documentation/tracking.html, znai-server/src/main/java/com/twosigma/znai/server/landing/LandingUrlContentHandler.java, znai-site-extensions/src/main/java/com/twosigma/znai/web/extensions/WebSiteResourcesProvider.java, znai-site-extensions/src/main/java/com/twosigma/znai/web/extensions/WebSiteResourcesProviders.java, znai/src/main/java/com/twosigma/znai/html/HtmlPage.java, znai/src/main/java/com/twosigma/znai/html/PageToHtmlPageConverter.java, znai/src/main/java/com/twosigma/znai/html/ServerSideSimplifiedRenderer.java, znai/src/main/java/com/twosigma/znai/html/reactjs/HtmlReactJsPage.java, znai/src/main/java/com/twosigma/znai/website/WebSiteUserExtensions.java, znai/src/main/resources/template/initial-page-loading.html, znai/src/test/groovy/com/twosigma/znai/html/HtmlPageTest.groovy, znai/src/test/groovy/com/twosigma/znai/html/ServerSideSimplifiedRendererTest.groovy, znai/src/test/groovy/com/twosigma/znai/website/WebSiteUserExtensionsTest.groovy
This is mostly so tracking extension could be added before anything else loaded.
There is one place where I didn't rename `htmlResources` to `htmlBodyResources` as there are some internal clients that may be using this already.  @jyeakel it would help if we could work with them and rename it while there are no outside users of this feature yet.
=> add custom html head extension

znai/src/main/java/com/twosigma/znai/website/WebSiteUserExtensions.java, znai/src/test/groovy/com/twosigma/znai/website/WebSiteUserExtensionsTest.groovy, znai/src/test/resources/style.css
as a shortcut users can define `style.css` for style overrides and/or `tracking.html` for javascript injection into `head`
=> add shortcut to user extensions for style and tracking

znai-reactjs/src/doc-elements/Documentation.js
Right now if you exit presentation mode and try to navigate to any page, scroll position will not jump to 0. 
Also scrolling within the page won't highlight section names in TOC.
Fix is not very React way and I think Default documentation Mode needs to be extracted in its own component so all the enabling/disabling logic will be handled using lifecycle methods. 
Plan is to add UI tests first and then we can start bigger refactoring.
=> re-enable scroll to top and section highlights after presentation mode

znai-reactjs/src/doc-elements/svg/Svg.js
First step on making SVGs more mobile friendly. 
This is so SVG width could be forced with outside CSS like `max-width: 100%` without creating extra gap due to already set height.
=> maintain only svg width when auto fit

znai-core/src/main/java/org/testingisdocumenting/znai/structure/DocUrl.java, znai-docs/znai/flow/page-references.md, znai/src/main/java/org/testingisdocumenting/znai/website/WebSiteDocStructure.java, znai/src/test/groovy/org/testingisdocumenting/znai/website/WebSiteDocStructureTest.groovy
=> fix linking to root of a documentation with an anchor

pom.xml, znai-enterprise/pom.xml, znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/EnterpriseComponentsRegistry.java, znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/ZnaiEnterpriseConfig.java, znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/docpreparation/StorageBasedDocumentationPreparationHandler.java, znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/monitoring/BuildOutputMonitor.java, znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/monitoring/BuildRootAndWildCardPatterns.java, znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/monitoring/FilesFinder.java, znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/monitoring/MonitorConfig.java, znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/storage/FileBasedDocumentationStorage.java, znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/upload/UnzipAndStoreOnUploadFinishedServerHandler.java, znai-enterprise/src/main/java/org/testingisdocumenting/znai/fs/FsUtils.java, znai-enterprise/src/main/java/org/testingisdocumenting/znai/fs/UnzipTask.java, znai-enterprise/src/main/resources/META-INF/services/org.testingisdocumenting.znai.server.ServerLifecycleListener, znai-enterprise/src/test/groovy/org/testingisdocumenting/znai/enterprise/monitoring/FilesFinderTest.groovy, znai-enterprise/src/test/groovy/org/testingisdocumenting/znai/enterprise/monitoring/MonitorConfigTest.groovy, znai-enterprise/src/test/resources/monitor.config.json, znai-server/src/main/java/org/testingisdocumenting/znai/server/ZnaiServerConfig.java
periodically checks specified directories and wild card patterns.
Once a new documentation zip is detected, unpacks it to temporary location to extract doc id (directory name) and store using active storage implementation.
Use case is to monitor bazel outputs assuming the output produces a zip archive on a filesystem that is visible to a znai enterprise server.
=> znai enterprise build output monitor for zip archives with docs

znai-core/src/main/java/org/testingisdocumenting/znai/extensions/file/FilePlugin.java, znai-core/src/test/groovy/org/testingisdocumenting/znai/extensions/file/FileIncludePluginTest.groovy, znai-core/src/test/resources/highlight.txt, znai-core/src/test/resources/sample-with-marker.py, znai-core/src/test/resources/sample-with-multi-marker.py, znai-core/src/test/resources/script.groovy, znai-docs/znai/snippets/external-code-snippets.md, znai-docs/znai/snippets/python-examples.py
@jyeakel please note new examples.
also `exclude` param to `include-file` was replaced with `excludeStartEnd`. They never were documented, so I hope no one is going to be affected.
=> add include-file start,end,include,exclude docs. add exclude by regexp(s)

znai-cli/src/main/java/org/testingisdocumenting/znai/cli/ZnaiCliConfig.java, znai-core/pom.xml, znai-core/src/main/java/org/testingisdocumenting/znai/version/ZnaiVersion.java, znai-core/src/main/resources/znai-version.txt
@byc1234 it may affect the output of your internal build. Since you are building from head most of the time `version` will contain `SNAPSHOT` suffix. 
A quick fix would be to use maven version plugin to set a version before build. 
Alternatively we can add a system property flag to remove SNAPSHOT or force a version.
=> print znai version and timestamp on start

znai-reactjs/src/doc-elements/presentation/Presentation.css, znai-reactjs/src/doc-elements/presentation/Presentation.js, znai-reactjs/src/doc-elements/presentation/PresenterMode.css, znai-reactjs/src/doc-elements/presentation/PresenterMode.tsx, znai-reactjs/src/doc-elements/presentation/SlidePanel.css, znai-reactjs/src/doc-elements/presentation/SlidePanel.tsx, znai-reactjs/src/doc-elements/presentation/presentationBroadcastChannel.ts
Presentation mode has now icon to switch to presenter mode.
You can open the same presentation on two different browsers and use presenter mode to see what's next two slides are.
Timer, notes extracted from documentation page and other features will be in a separate PR
=> presentation: initial presenter mode

znai-docs/znai/snippets/python.md, znai-python/src/main/java/org/testingisdocumenting/znai/python/PythonBasedPythonParser.java, znai-python/src/main/resources/python_parser.py
A few changes in this PR:
1. make the parsing not fail on python 3.7 (and likely earlier too). Full functionality isn’t available, only docstring but we’ll print an appropriate warning
2. improved excepting handling to include stack trace as well as the name of the class or function
3. changed the response schema too communicate errors and warnings back from the python parser script
4. added logging of warnings and error as appropriate
=> python: parser improvements 

znai-docs/znai/release-notes/1.50/add-2021-06-15-python-function.md, znai-docs/znai/release-notes/1.52/add-2021-07-12-py-vars.md, znai-docs/znai/release-notes/2021.md, znai-docs/znai/snippets/python.md, znai-docs/znai/snippets/python/example.py, znai-python/src/main/resources/python_parser.py, znai-python/src/test/groovy/org/testingisdocumenting/znai/python/PythonBasedPythonParserTest.groovy, znai-python/src/test/groovy/org/testingisdocumenting/znai/python/PythonDocIncludePluginTest.groovy, znai-python/src/test/groovy/org/testingisdocumenting/znai/python/PythonIncludePluginTest.groovy, znai-python/src/test/resources/example.py
In this initial implementation, I'm intentionally not supporting things like this:
```python
a, b = foo()
```
=> python: support extraction of assignments

znai-core/src/main/java/org/testingisdocumenting/znai/parser/docelement/DocElementCreationParserHandler.java, znai-core/src/test/groovy/org/testingisdocumenting/znai/parser/MarkdownParserTest.groovy, znai-core/src/test/resources/images/test.svg, znai-docs/znai/release-notes/1.63/fix-2023-02-21-image-svg-null-pointer.md, znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/image/ImagePluginBase.java
=> images: fix svg null pointer when using include plugin

pom.xml, znai-docs/znai/znai-development/local-build.md, znai-typescript/pom.xml
- add documentation about how to install `firefox` so that the tests using selenium can be executed sucessfully
- document that we need Java 17 to build, not Java 8 any more
- fix an issue where node is not found in the `znai-typescript` module
=> Improve local build documentation and fix build issue
