pom.xml
znai-groovy/pom.xml
znai-maven-plugin/pom.xml
znai-testing-tcli/pom.xml

I think this should fix the release stuff, fingers crossed.

Groovy auto gen profile

---

znai-docs/documentation/toc
znai-docs/documentation/visuals/keyboard-shortcuts.md
znai-reactjs/src/App.js
znai-reactjs/src/doc-elements/DefaultElementsLibrary.js
znai-reactjs/src/doc-elements/keyboard/KeyboardShortcut.css
znai-reactjs/src/doc-elements/keyboard/KeyboardShortcut.demo.js
znai-reactjs/src/doc-elements/keyboard/KeyboardShortcut.js
znai/src/main/java/com/twosigma/znai/extensions/keyboard/KeyboardShortcutInlinedCodePlugin.java
znai/src/main/resources/META-INF/services/com.twosigma.znai.extensions.inlinedcode.InlinedCodePlugin

@jyeakel please update styles.
to live preview `npm start` in `znai-reactjs` and open http://localhost:3000/?_rcv_rname=visuals&_rcv_dname=Keyboard+shortcuts&_rcv_dropdown_theme=default

initial <keyboard shortcut> inlined code plugin

---

znai-reactjs/src/doc-elements/DefaultElementsLibrary.js
znai-reactjs/src/index.js

This is to be able to register different page types by 3rd party

expose elementsLibrary through global var for extensions

---

pom.xml

This is another security patch. I am enabling an automated pull request creation, but not sure how it will deal with multi maven project and transitive deps.

apache commons compress deps patch

---

znai-reactjs/src/doc-elements/DefaultElementsLibrary.js
znai-reactjs/src/doc-elements/page/default/DefaultPageContent.js
znai-reactjs/src/doc-elements/page/two-sides/TwoSidesPageContent.js

expose PageTitle through elementsLibrary

---

znai-reactjs/src/doc-elements/json/Json.demo.js
znai-reactjs/src/doc-elements/json/jsonPrinter.js

fix include-json null value

---

znai-cli/src/main/java/com/twosigma/znai/cli/ZnaiCliApp.java
znai-core/src/main/java/com/twosigma/znai/extensions/file/CodeReferencesTrait.java
znai-core/src/main/java/com/twosigma/znai/extensions/file/FileIncludePlugin.java
znai-core/src/main/java/com/twosigma/znai/reference/DocReferences.java
znai-core/src/main/java/com/twosigma/znai/reference/DocReferencesParser.java
znai-core/src/main/java/com/twosigma/znai/reference/GlobalDocReferences.java
znai-core/src/test/groovy/com/twosigma/znai/extensions/file/CodeReferencesTraitTest.groovy
znai-core/src/test/groovy/com/twosigma/znai/reference/DocReferencesParserTest.groovy
znai-docs/documentation/example-references/api.md
znai-docs/documentation/references.csv
znai-docs/documentation/snippets/code-references.md
znai-docs/documentation/snippets/external-code-snippets.md
znai-docs/documentation/snippets/global-references.js
znai-docs/documentation/snippets/java-doc.md
znai-docs/documentation/toc
znai-groovy/src/main/groovy/com/twosigma/znai/groovy/extensions/GroovyIncludePlugin.groovy
znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaDocParamsIncludePlugin.java
znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaIncludePlugin.java
znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaIncludePluginBase.java
znai-reactjs/src/doc-elements/Documentation.js
znai-reactjs/src/doc-elements/code-snippets/CodeSnippetWithInlineComments.js
znai-reactjs/src/doc-elements/code-snippets/SimpleCodeSnippet.js
znai-reactjs/src/doc-elements/preview/Preview.js
znai-reactjs/src/doc-elements/references/globalDocReferences.js
znai-server/src/main/java/com/twosigma/znai/server/preview/DocumentationPreview.java
znai-server/src/main/java/com/twosigma/znai/server/preview/FileWatcher.java
znai-server/src/main/java/com/twosigma/znai/server/preview/PreviewPushFileChangeHandler.java
znai-server/src/main/java/com/twosigma/znai/server/preview/PreviewWebSocketHandler.java
znai/src/main/java/com/twosigma/znai/website/WebSite.java

add support for global doc references file

---

znai-core/src/main/java/com/twosigma/znai/extensions/reveal/SpoilerFencePlugin.java
znai-core/src/main/resources/META-INF/services/com.twosigma.znai.extensions.fence.FencePlugin
znai-docs/documentation/toc
znai-docs/documentation/visuals/spoilers.md
znai-reactjs/src/App.js
znai-reactjs/src/doc-elements/DefaultElementsLibrary.js
znai-reactjs/src/doc-elements/code-snippets/BulletExplanations.js
znai-reactjs/src/doc-elements/spoiler/Spoiler.css
znai-reactjs/src/doc-elements/spoiler/Spoiler.demo.js
znai-reactjs/src/doc-elements/spoiler/Spoiler.js

add spoiler plugin

---

znai-diagrams/src/main/java/com/twosigma/znai/diagrams/graphviz/gen/DiagramNode.java
znai-diagrams/src/main/java/com/twosigma/znai/diagrams/graphviz/gen/GraphvizFromJsonGen.java
znai-diagrams/src/main/java/com/twosigma/znai/diagrams/graphviz/gen/NodesConfig.java
znai-diagrams/src/test/groovy/com/twosigma/znai/diagrams/graphviz/gen/GraphvizFromJsonGenTest.groovy
znai-docs/documentation/visuals/flow-diagrams.md
znai-docs/documentation/visuals/flow-diagrams/common-size-dag.json
znai-docs/documentation/visuals/flow-diagrams/common-size-with-override-dag.json

flow diagram nodes size

---

znai-docs/documentation/layout/tables.md
znai-reactjs/src/App.css
znai-reactjs/src/doc-elements/table/Table.css
znai-reactjs/src/doc-elements/table/Table.demo.js
znai-reactjs/src/doc-elements/table/Table.js
znai-reactjs/src/theme/znai-dark/znai-dark.css
znai/src/main/java/com/twosigma/znai/extensions/table/TableIncludePlugin.java

add table title param

---

znai-core/src/main/java/com/twosigma/znai/extensions/PluginParamsOpts.java
znai-docs/documentation/snippets/CLI.md
znai-reactjs/src/doc-elements/cli/CliCommand.demo.js
znai-reactjs/src/doc-elements/cli/CliCommand.js
znai-reactjs/src/utils/strings.js
znai-reactjs/src/utils/strings.test.js
znai/src/main/java/com/twosigma/znai/extensions/cli/CliCommandIncludePlugin.java
znai/src/test/groovy/com/twosigma/znai/extensions/cli/CliCommandIncludePluginTest.groovy

* increased wrap number of chars to 100
* expose option to set number of chars before wrap
* let to force wrap after specified param names
* validates highlight keywords to be present
closes #31

add cli command threshold and splitAfter options. default threshold is 80 -> 100

---

znai-core/src/main/java/com/twosigma/znai/parser/docelement/DocElementCreationParserHandler.java
znai-core/src/main/java/com/twosigma/znai/structure/DocStructure.java
znai-core/src/main/java/com/twosigma/znai/structure/DocUrl.java
znai-core/src/test/groovy/com/twosigma/znai/parser/TestDocStructure.groovy
znai-diagrams/src/main/java/com/twosigma/znai/diagrams/FlowChartIncludePlugin.java
znai-docs/documentation/flow/page-references.md
znai-reactjs/src/doc-elements/structure/DocumentationNavigation.js
znai/src/main/java/com/twosigma/znai/website/WebSite.java
znai/src/main/java/com/twosigma/znai/website/WebSiteDocStructure.java
znai/src/test/groovy/com/twosigma/znai/website/WebSiteDocStructureTest.groovy

support shortcut linking to a section within a page

---

znai-docs/documentation/example-references/domain.md
znai-docs/documentation/snippets/MyEnum.java
znai-docs/documentation/snippets/TransactionTypes.java
znai-docs/documentation/snippets/java-doc.md
znai-docs/documentation/snippets/references/javadoc-references-demo.csv
znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaDocParamsIncludePlugin.java
znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaEnumEntriesIncludePlugin.java
znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaIncludePluginBase.java
znai-java/src/test/groovy/com/twosigma/znai/java/extensions/JavaEnumEntriesIncludePluginTest.groovy
znai-reactjs/src/doc-elements/api/ApiParameter.css
znai-reactjs/src/doc-elements/api/ApiParameter.js
znai-reactjs/src/doc-elements/api/ApiParameters.demo.js

Enum entries use api params

---

znai-core/src/main/java/com/twosigma/znai/extensions/api/ApiParametersFencePlugin.java
znai-core/src/main/java/com/twosigma/znai/extensions/api/ApiParametersIncludePlugin.java
znai-docs/documentation/snippets/api-parameters.md
znai-docs/documentation/snippets/java-doc.md
znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaDocParamsIncludePlugin.java
znai-java/src/main/java/com/twosigma/znai/java/extensions/JavaEnumEntriesIncludePlugin.java
znai-java/src/test/groovy/com/twosigma/znai/java/extensions/JavaEnumEntriesIncludePluginTest.groovy
znai-reactjs/src/App.css
znai-reactjs/src/doc-elements/api/ApiParameters.css
znai-reactjs/src/doc-elements/api/ApiParameters.demo.js
znai-reactjs/src/doc-elements/api/ApiParameters.js
znai-reactjs/src/theme/znai-dark/znai-dark.css

Add title parameter to 
* api parameters
* enum entries
*  java params
Also changed inner border color slightly for dark theme (to be more aligned with light theme).

Api params title

---

znai-reactjs/src/App.js
znai-reactjs/src/doc-elements/Documentation.js
znai-reactjs/src/doc-elements/default-elements/Paragraph.demo.js
znai-reactjs/src/doc-elements/page/default/PageDefaultNextPrevNavigation.demo.js
znai-reactjs/src/doc-elements/page/default/PageDefaultNextPrevNavigation.js
znai-reactjs/src/doc-elements/page/two-sides/TwoSidesNextPrevNavigation.demo.js
znai-reactjs/src/doc-elements/page/two-sides/TwoSidesNextPrevNavigation.js

add chapter title to next/prev nav when crossing chapters

---

znai-reactjs/src/doc-elements/code-snippets/SimpleCodeSnippet.js

collapse read more during preview on readMoreVisibleLines change

---

znai-reactjs/src/theme/znai-dark/znai-dark.css

dark theme token colors to match overall theme

---

znai-enterprise/pom.xml
znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/EnterpriseComponentsRegistry.java
znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/docpreparation/StorageBasedDocumentationPreparationHandler.java
znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/storage/DocumentationStorage.java
znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/storage/FileBasedDocumentationStorage.java
znai-enterprise/src/main/java/org/testingisdocumenting/znai/enterprise/upload/UnzipAndStoreOnUploadFinishedServerHandler.java
znai-enterprise/src/main/resources/META-INF/services/org.testingisdocumenting.znai.server.ServerLifecycleListener
znai-enterprise/src/main/resources/META-INF/services/org.testingisdocumenting.znai.server.docpreparation.DocumentationPreparationHandler
znai-server/src/main/java/org/testingisdocumenting/znai/server/ServerLifecycleListener.java
znai-server/src/main/java/org/testingisdocumenting/znai/server/ServerLifecycleListeners.java
znai-server/src/main/java/org/testingisdocumenting/znai/server/ZnaiServer.java
znai-server/src/main/java/org/testingisdocumenting/znai/server/ZnaiServerConfig.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/html/Deployer.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/website/DocumentationFileBasedTimestamp.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/website/WebSite.java

Version as additional parameters there are for future thinking only. Not being used at the moment.

enterprise file based storage and doc timestamp

---

znai-reactjs/src/doc-elements/Documentation.js
znai-reactjs/src/doc-elements/page/default/PageDefaultNextPrevNavigation.demo.js
znai-reactjs/src/doc-elements/page/default/PageDefaultNextPrevNavigation.js
znai-reactjs/src/doc-elements/page/two-sides/TwoSidesNextPrevNavigation.js
znai-reactjs/src/structure/DocumentationNavigation.js
znai-reactjs/src/structure/toc/TableOfContents.test.ts
znai-reactjs/src/structure/toc/TableOfContents.ts

enable prev page to index

---

znai-reactjs/src/App.js
znai-reactjs/src/doc-elements/code-snippets/CodeSnippetSyntaxHighlight.demo.js
znai-reactjs/src/doc-elements/code-snippets/codeParser.js

syntax highlight: protobuf

---

znai-core/src/main/java/org/testingisdocumenting/znai/parser/commonmark/MarkdownVisitor.java
znai-core/src/main/java/org/testingisdocumenting/znai/parser/commonmark/ValidateNoExtraSyntaxInHeadingVisitor.java
znai-core/src/test/groovy/org/testingisdocumenting/znai/parser/MarkdownParserTest.groovy

validation: validate no extra syntax in heading

---

znai-website-gen/src/main/java/org/testingisdocumenting/znai/website/WebSite.java

generation: fix all-pages.json order

---

pom.xml
znai-diagrams/src/main/java/org/testingisdocumenting/znai/diagrams/plantuml/PlantUml.java
znai-docs/znai/flow/lookup-paths.md
znai-docs/znai/visuals/PlantUml.md
znai-docs/znai/visuals/gantt.plantuml

plugins: upgrade plantuml to work with gantt

---

znai-docs/znai/snippets/api-parameters.md

snippets: multi line api-parameters example

---

znai-docs/znai/layout/table/table-mapping.csv
znai-docs/znai/layout/tables.md
znai-docs/znai/visuals/icons.md
znai-reactjs/src/App.css
znai-reactjs/src/doc-elements/bullets/BulletList.demo.js
znai-reactjs/src/doc-elements/bullets/BulletList.js
znai-reactjs/src/doc-elements/bullets/ListItem.css
znai-reactjs/src/doc-elements/bullets/ListItem.js
znai-reactjs/src/doc-elements/bullets/bulletUtils.js
znai-reactjs/src/doc-elements/bullets/kinds/DefaultBulletList.js
znai-reactjs/src/doc-elements/default-elements/DocElement.js
znai-reactjs/src/doc-elements/default-elements/SectionTitle.css
znai-reactjs/src/doc-elements/default-elements/SubHeading.css
znai-reactjs/src/doc-elements/icons/Icon.css
znai-reactjs/src/doc-elements/icons/Icon.tsx
znai-reactjs/src/doc-elements/page/default/PageDefaultNextPrevNavigation.css
znai-reactjs/src/doc-elements/paragraph/Paragraph.css
znai-reactjs/src/doc-elements/paragraph/Paragraph.demo.js
znai-reactjs/src/layout/TocPanelSearch.css
znai-reactjs/src/theme/znai-dark/znai-dark.css
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/icons/IconInlinedCodePlugin.java

visuals: add icon colors

---

znai-docs/znai/snippets/api-parameters.md
znai-reactjs/src/doc-elements/api/ApiParameter.css
znai-reactjs/src/doc-elements/api/ApiParameters.css
znai-reactjs/src/doc-elements/api/ApiParameters.demo.js
znai-reactjs/src/doc-elements/api/ApiParameters.js

snippets: api-parameters size param

---

znai-website-gen/src/main/java/org/testingisdocumenting/znai/html/reactjs/HtmlReactJsPage.java

snippet: fix html/xml snippets with <script> tag

---

znai-core/src/main/java/org/testingisdocumenting/znai/parser/PageSectionIdTitle.java
znai-core/src/main/java/org/testingisdocumenting/znai/parser/docelement/DocElementCreationParserHandler.java
znai-core/src/main/java/org/testingisdocumenting/znai/parser/docelement/SubHeadingUniqueIdGenerator.java
znai-core/src/test/groovy/org/testingisdocumenting/znai/parser/MarkdownParserTest.groovy
znai-docs/znai/flow/page-references.md
znai-docs/znai/snippets/references/javadoc-references-demo.csv

structure: unique sub-heading ids

---

znai-reactjs/src/App.css
znai-reactjs/src/doc-elements/code-snippets/CodeSnippetSyntaxHighlight.demo.js
znai-reactjs/src/doc-elements/code-snippets/codeParser.js
znai-reactjs/src/doc-elements/code-snippets/tokens.css
znai-reactjs/src/theme/znai-dark/znai-dark.css

snippet: highlight diff

---

znai-core/src/main/java/org/testingisdocumenting/znai/extensions/file/FileIncludePlugin.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/file/SnippetAutoTitleFeature.java
znai-core/src/test/groovy/org/testingisdocumenting/znai/extensions/file/FileIncludePluginTest.groovy
znai-docs/znai/snippets/external-code-snippets.md
znai-groovy/src/main/groovy/org/testingisdocumenting/znai/groovy/extensions/GroovyIncludePlugin.groovy
znai-groovy/src/test/groovy/org/testingisdocumenting/znai/groovy/extensions/GroovyIncludePluginTest.groovy
znai-java/src/main/java/org/testingisdocumenting/znai/java/extensions/JavaIncludePlugin.java
znai-java/src/test/groovy/org/testingisdocumenting/znai/java/extensions/JavaIncludePluginTest.groovy

snippet: auto title feature

---

znai-core/src/main/java/org/testingisdocumenting/znai/search/SearchCrawlerParserHandler.java

fix: include subheadings in znai index

---

znai-diagrams/src/main/java/org/testingisdocumenting/znai/diagrams/mermaid/MermaidFencePlugin.java
znai-diagrams/src/main/resources/META-INF/services/org.testingisdocumenting.znai.extensions.fence.FencePlugin
znai-docs/znai/toc
znai-docs/znai/visuals/mermaid.md
znai-reactjs/package-lock.json
znai-reactjs/package.json
znai-reactjs/src/App.js
znai-reactjs/src/doc-elements/DefaultElementsLibrary.js
znai-reactjs/src/doc-elements/mermaid/Mermaid.demo.js
znai-reactjs/src/doc-elements/mermaid/Mermaid.js

Add support for Mermaid, see #600

visuals: add support for Mermaid js

---

pom.xml
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/PluginParams.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/PluginParamsOpts.java
znai-core/src/main/java/org/testingisdocumenting/znai/parser/docelement/DocElement.java
znai-core/src/test/groovy/org/testingisdocumenting/znai/extensions/PluginParamsOptsTest.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/parser/TestResourceResolver.groovy
znai-docs/znai/snippets/python.md
znai-docs/znai/snippets/python/example.py
znai-docs/znai/toc
znai-python/pom.xml
znai-python/src/main/java/org/testingisdocumenting/znai/python/PythonBasedPythonParser.java
znai-python/src/main/java/org/testingisdocumenting/znai/python/PythonDocIncludePlugin.java
znai-python/src/main/resources/META-INF/services/org.testingisdocumenting.znai.extensions.include.IncludePlugin
znai-python/src/main/resources/python_parser.py
znai-python/src/test/groovy/org/testingisdocumenting/znai/python/PythonBasedPythonParserTest.groovy
znai-python/src/test/groovy/org/testingisdocumenting/znai/python/PythonDocIncludePluginTest.groovy
znai-python/src/test/resources/example.py
znai-typescript/src/main/java/org/testingisdocumenting/znai/typescript/TypeScriptIncludePlugin.java
znai-typescript/src/main/java/org/testingisdocumenting/znai/typescript/TypescriptNodeBasedParser.java
znai-typescript/src/test/groovy/org/testingisdocumenting/znai/typescript/TypeScriptIncludePluginTest.groovy
znai-utils/src/main/java/org/testingisdocumenting/znai/utils/ResourceUtils.java
znai-website-gen/pom.xml

python: add include python-doc

---

znai-core/src/main/java/org/testingisdocumenting/znai/extensions/validation/EntryPresenceValidation.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/json/JsonIncludePlugin.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/json/JsonPaths.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/xml/XmlIncludePlugin.java
znai-website-gen/src/test/groovy/org/testingisdocumenting/znai/extensions/json/JsonIncludePluginTest.groovy
znai-website-gen/src/test/resources/jsonFileWithPaths.json

json: validate path presence

---

znai-reactjs/src/diff/DiffTracking.demo.js
znai-reactjs/src/diff/DiffTracking.js
znai-reactjs/src/doc-elements/Documentation.js
znai-reactjs/src/layout/DocumentationLayout.css
znai-reactjs/src/layout/DocumentationLayout.tsx
znai-reactjs/src/layout/classNames.ts
znai-reactjs/src/structure/DocumentationNavigation.js
znai-tests/src/test/groovy/pages/StandardView.groovy
znai-tests/src/test/groovy/scenarios/navigation.groovy

@evinaik example of a fix and UI test

site: restore scroll position on back button

---

znai-python/src/main/resources/python_parser.py
znai-python/src/test/groovy/org/testingisdocumenting/znai/python/PythonDocIncludePluginTest.groovy
znai-python/src/test/groovy/org/testingisdocumenting/znai/python/PythonIncludePluginTest.groovy
znai-python/src/test/resources/example.py

python: fix pass handling

---

znai-diagrams/src/main/java/org/testingisdocumenting/znai/diagrams/graphviz/GraphvizDiagram.java
znai-diagrams/src/main/java/org/testingisdocumenting/znai/diagrams/graphviz/gen/GraphvizFromJsonGen.java
znai-diagrams/src/main/java/org/testingisdocumenting/znai/diagrams/graphviz/meta/GraphvizDiagramWithMeta.java
znai-diagrams/src/test/groovy/org/testingisdocumenting/znai/diagrams/graphviz/GraphvizEngineTest.groovy
znai-diagrams/src/test/groovy/org/testingisdocumenting/znai/diagrams/graphviz/gen/GraphvizFromJsonGenTest.groovy
znai-diagrams/src/test/groovy/org/testingisdocumenting/znai/diagrams/graphviz/meta/GraphvizDiagramWithMetaTest.groovy
znai-docs/znai/release-notes/1.51/_fix-2021-07-03-flow-diagram-dash.md
znai-docs/znai/visuals/flow-diagrams/simple-dag-shapes.json
znai-utils/src/main/java/org/testingisdocumenting/znai/utils/StringUtils.java
znai-utils/src/test/groovy/org/testingisdocumenting/znai/utils/StringUtilsTest.groovy

diagram: flow chart fix for ids with dashes

---

znai-docs/znai/layout/tables.md
znai-docs/znai/release-notes/1.52/add-2021-07-22-table-column-min-width.md
znai-reactjs/src/doc-elements/table/Table.demo.tsx
znai-reactjs/src/doc-elements/table/Table.tsx
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/table/TableDocElementFromParams.java

layout: tables columns min width

---

znai-reactjs/src/doc-elements/search/Search.js

maintenance: remove last mdoc ref

---

znai-docs/znai/release-notes/1.53/_fix-2021-09-08-python-data-classes.md
znai-docs/znai/release-notes/2021.md

I forgot release notes in #675.

doc: add release notes for PR #675

---

znai-docs/znai/footer.md
znai-docs/znai/release-notes/1.54/add-2021-09-17-tabs-validation.md
znai-docs/znai/snippets/external-code-snippets.md
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/tabs/TabsFencePlugin.java
znai-website-gen/src/test/groovy/org/testingisdocumenting/znai/extensions/tabs/TabsFencePluginTest.groovy

tabs: add entries presence validation

---

znai-core/src/main/java/org/testingisdocumenting/znai/parser/HeadingPayload.java
znai-core/src/main/java/org/testingisdocumenting/znai/parser/HeadingPayloadList.java
znai-core/src/main/java/org/testingisdocumenting/znai/parser/NoOpParserHandler.java
znai-core/src/main/java/org/testingisdocumenting/znai/parser/ParserHandler.java
znai-core/src/main/java/org/testingisdocumenting/znai/parser/ParserHandlersList.java
znai-core/src/main/java/org/testingisdocumenting/znai/parser/commonmark/MarkdownVisitor.java
znai-core/src/main/java/org/testingisdocumenting/znai/parser/commonmark/ValidateNoExtraSyntaxExceptInlineCodeInHeadingVisitor.java
znai-core/src/main/java/org/testingisdocumenting/znai/parser/docelement/DocElementCreationParserHandler.java
znai-core/src/main/java/org/testingisdocumenting/znai/search/SearchCrawlerParserHandler.java
znai-core/src/test/groovy/org/testingisdocumenting/znai/parser/MarkdownParserTest.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/search/SearchCrawlerParserHandlerTest.groovy
znai-docs/znai/release-notes/1.54/add-2021-11-04-text-badge-header.md
znai-docs/znai/visuals/text-badge.md
znai-open-api/src/main/java/org/testingisdocumenting/znai/openapi/OpenApiIncludePlugin.java
znai-reactjs/src/doc-elements/default-elements/Section.js
znai-reactjs/src/doc-elements/default-elements/SectionTitle.css
znai-reactjs/src/doc-elements/default-elements/SectionTitle.js
znai-reactjs/src/doc-elements/default-elements/SubHeading.js
znai-reactjs/src/doc-elements/page/two-sides/TwoSidesSection.js
znai-reactjs/src/doc-elements/typography/Typography.demo.js
znai-sphinx/src/main/java/org/testingisdocumenting/znai/parser/sphinx/DocTreeDomXmlParser.java
znai-sphinx/src/test/groovy/org/testingisdocumenting/znai/parser/sphinx/SphinxDocTreeParserTest.groovy
znai-website-gen/src/test/groovy/org/testingisdocumenting/znai/extensions/templates/TemplateIncludePluginTest.groovy

visuals: heading text badge

---

znai-docs/znai/release-notes/1.54/add-2021-11-14-javadoc-field-ambig.md
znai-docs/znai/snippets/HelloWorldWithInner.java
znai-docs/znai/snippets/java-doc.md
znai-java/src/main/java/org/testingisdocumenting/znai/java/parser/EnumEntry.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/parser/JavaCodeVisitor.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/parser/JavaField.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/parser/JavaIdentifier.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/parser/JavaMethod.java
znai-java/src/test/groovy/org/testingisdocumenting/znai/java/extensions/JavaDocIncludePluginTest.groovy
znai-java/src/test/groovy/org/testingisdocumenting/znai/java/parser/JavaCodeTest.groovy
znai-java/src/test/groovy/org/testingisdocumenting/znai/java/parser/JavaIdentifierTest.groovy
znai-java/src/test/groovy/org/testingisdocumenting/znai/java/parser/JavaMethodTest.groovy
znai-java/src/test/resources/WithJavaDocs.java

javadoc: handle of inner class methods/fields

---

znai-docs/znai/release-notes/1.56/fix-2022-02-01-search-special-chars.md
znai-reactjs/package-lock.json
znai-reactjs/package.json
znai-reactjs/src/doc-elements/search/Search.js

closes #743 
@byc1234 please check when you have time

search: quote special chars + upgrade lunr

---

znai-docs/znai/release-notes/1.56/add-2022-02-06-open-api-loop.md
znai-docs/znai/toc
znai-open-api/src/main/java/org/testingisdocumenting/znai/openapi/OpenApiSpec.java
znai-open-api/src/test/groovy/org/testingisdocumenting/znai/openapi/OpenApiRefLoopTest.groovy
znai-open-api/src/test/resources/open-api-spec-loop.json
znai-reactjs/src/doc-elements/open-api/schema/OpenApiSchema.data.demo.js
znai-reactjs/src/doc-elements/open-api/schema/schemaToApiParameters.test.js

openapi: handle loop

---

znai-docs/znai/release-notes/1.57/add-2022-05-08-wrap-code.md
znai-docs/znai/snippets/code-snippets.md
znai-docs/znai/snippets/external-code-snippets.md
znai-reactjs/src/doc-elements/code-snippets/CodeSnippetWithInlineComments.demo.js
znai-reactjs/src/doc-elements/code-snippets/CodeSnippetWithInlineComments.js
znai-reactjs/src/doc-elements/code-snippets/LineOfTokens.css
znai-reactjs/src/doc-elements/code-snippets/LineOfTokens.js
znai-reactjs/src/doc-elements/code-snippets/SimpleCodeSnippet.js
znai-reactjs/src/doc-elements/code-snippets/Snippet.demo.js
znai-reactjs/src/doc-elements/code-snippets/SnippetOptionallyScrollablePart.tsx
znai-reactjs/src/doc-elements/code-snippets/tokens.css

snippet: wrap lines option

---

znai-docs/znai/release-notes/1.57/fix-2022-05-18-read-more-preview.md
znai-reactjs/src/doc-elements/code-snippets/SimpleCodeSnippet.js
znai-reactjs/src/doc-elements/code-snippets/Snippet.demo.js

snippet: readmore proper update during preview

---

znai-docs/znai/release-notes/1.57/add-2022-05-18-steps-bullets-align.md
znai-docs/znai/visuals/smart-bullet-points.md
znai-reactjs/src/App.js
znai-reactjs/src/doc-elements/bullets/BulletList.demo.js
znai-reactjs/src/doc-elements/bullets/SmarlBulletList.demo.tsx
znai-reactjs/src/doc-elements/bullets/kinds/Steps.js

smartbullets: align option for steps

---

znai-docs/znai/flow/support.md
znai-docs/znai/meta.json
znai-docs/znai/release-notes/1.58/add-2022-06-20-support-title.md
znai-reactjs/src/doc-elements/page/PageTitle.js
znai-reactjs/src/doc-elements/page/Support.tsx
znai-reactjs/src/doc-elements/testDocumentation.js
znai-reactjs/src/structure/docMeta.ts

@byc1234 please check this out as it may affect you

flow: add support title option

---

znai-docs/znai/release-notes/1.58/add-2022-07-01-readmore-collapse.md
znai-reactjs/src/doc-elements/code-snippets/SimpleCodeSnippet.js

snippets: collapse button after read more

---

znai-docs/znai/release-notes/1.59/fix-2022-07-22-image-zoom-vertical-scroll.md
znai-reactjs/src/doc-elements/images/AnnotatedImage.css
znai-reactjs/src/doc-elements/images/Image.demo.js
znai-reactjs/src/doc-elements/zoom/ZoomOverlay.css

images: fix vertical scroll for zoom-in tall images

---

znai-core/src/main/java/org/testingisdocumenting/znai/search/PageSearchEntries.java
znai-core/src/main/java/org/testingisdocumenting/znai/structure/PlainTextTocGenerator.java
znai-core/src/main/java/org/testingisdocumenting/znai/structure/PlainTextTocPatcher.java
znai-core/src/main/java/org/testingisdocumenting/znai/structure/TableOfContents.java
znai-core/src/main/java/org/testingisdocumenting/znai/structure/TocItem.java
znai-core/src/main/java/org/testingisdocumenting/znai/structure/TocNameAndOpts.java
znai-core/src/test/groovy/org/testingisdocumenting/znai/AuxiliaryFilesRegistryTest.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/extensions/toc/PageTocIncludePluginTest.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/search/PageSearchEntriesTest.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/structure/PlainTextTocGeneratorTest.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/structure/PlainTextTocPatcherTest.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/structure/TableOfContentsTest.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/structure/TocItemTest.groovy
znai-docs/znai/flow/names.md
znai-docs/znai/release-notes/1.59/add-2022-07-25-chapter-title-override.md
znai-reactjs/src/layout/TocMenu.js
znai-website-gen/src/main/java/org/testingisdocumenting/znai/website/WebSite.java
znai-website-gen/src/test/groovy/org/testingisdocumenting/znai/html/ServerSideSimplifiedRendererTest.groovy
znai-website-gen/src/test/groovy/org/testingisdocumenting/znai/website/WebSiteDocStructureTest.groovy

flow: chapter title override

---

znai-docs/znai/release-notes/1.60/fix-2022-08-21-api-params-empty-names.md
znai-reactjs/src/doc-elements/api/ApiParameters.demo.js
znai-reactjs/src/doc-elements/api/ApiParameters.tsx

apiparams: fix possible duplication when param names match

---

znai-docs/znai/release-notes/1.60/fix-2022-08-22-api-params-fence-inside-tabs.md
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/ColonDelimitedKeyValues.java
znai-website-gen/src/test/groovy/org/testingisdocumenting/znai/extensions/tabs/TabsFencePluginTest.groovy
znai-website-gen/src/test/groovy/org/testingisdocumenting/znai/extensions/templates/ColonDelimitedKeyValuesTest.groovy

tabs: fix confusion of fence block params with tab name

---

znai-docs/znai/release-notes/1.60/fix-2022-08-22-chapter-name-render-fix.md
znai-reactjs/src/doc-elements/page/default/PageDefaultNextPrevNavigation.js
znai-tests/src/test/groovy/pages/StandardView.groovy
znai-tests/src/test/groovy/scenarios/docsContent.groovy

site: render next/prev pages chapter instead of undefined

---

pom.xml
znai-docs/znai/release-notes/1.60/add-2022-08-21-plant-uml-bump.md

plantuml: version bump 1.2022.6

---

znai-docs/znai/release-notes/1.60/add-2022-08-22-attention-sign-tip.md
znai-docs/znai/visuals/attention-signs.md
znai-reactjs/src/App.css
znai-reactjs/src/doc-elements/paragraph/Paragraph.css
znai-reactjs/src/doc-elements/paragraph/Paragraph.demo.js
znai-reactjs/src/doc-elements/paragraph/Paragraph.tsx

attentionsigns: add tip and recommendation

---

znai-core/src/main/java/org/testingisdocumenting/znai/extensions/attention/AttentionSignAvoidFencePlugin.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/attention/AttentionSignFencePluginBase.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/attention/AttentionSignNoteFencePlugin.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/attention/AttentionSignQuestionFencePlugin.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/attention/AttentionSignRecommendationFencePlugin.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/attention/AttentionSignWarningFencePlugin.java
znai-core/src/main/resources/META-INF/services/org.testingisdocumenting.znai.extensions.fence.FencePlugin
znai-docs/znai/release-notes/1.60/add-2022-08-23-attention-sign-block.md
znai-docs/znai/visuals/attention-signs.md

attentionsign: fence block plugin

---

znai-core/src/main/java/org/testingisdocumenting/znai/extensions/features/PluginFeature.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/file/AnchorPluginFeature.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/file/FileIncludePlugin.java
znai-docs/znai/release-notes/1.60/add-2022-08-24-external-code-snippet-anchor.md
znai-docs/znai/snippets/external-code-snippets.md
znai-reactjs/src/doc-elements/code-snippets/Snippet.demo.js
znai-reactjs/src/doc-elements/code-snippets/SnippetContainer.css
znai-reactjs/src/doc-elements/code-snippets/SnippetContainer.js

snippets: external snippet anchor link

---

znai-docs/znai/layout/tables.md
znai-docs/znai/release-notes/1.60/add-2022-08-30-table-anchor.md
znai-reactjs/src/doc-elements/table/Table.css
znai-reactjs/src/doc-elements/table/Table.demo.tsx
znai-reactjs/src/doc-elements/table/Table.tsx
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/table/TableDocElementFromParams.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/table/TableFencePlugin.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/table/TableIncludePlugin.java

tables: add anchor support

---

znai-core/src/main/java/org/testingisdocumenting/znai/extensions/file/AnchorFeature.java
znai-core/src/main/java/org/testingisdocumenting/znai/parser/docelement/DocElementCreationParserHandler.java
znai-core/src/main/java/org/testingisdocumenting/znai/structure/DocStructure.java
znai-core/src/main/java/org/testingisdocumenting/znai/structure/UniqueAnchorIdGenerator.java
znai-core/src/main/java/org/testingisdocumenting/znai/utils/NameUtils.java
znai-core/src/test/groovy/org/testingisdocumenting/znai/parser/MarkdownParserTest.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/parser/TestDocStructure.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/structure/UniqueAnchorIdGeneratorTest.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/utils/NameUtilsTest.groovy
znai-docs/znai/layout/tables.md
znai-docs/znai/release-notes/1.51/doc-2021-06-26-brew.md
znai-docs/znai/release-notes/1.58/add-2022-07-08-python-method-def.md
znai-docs/znai/release-notes/1.58/add-2022-07-12-python-class-properties.md
znai-docs/znai/release-notes/1.60/add-2022-09-09-auto-anchor-from-title.md
znai-docs/znai/snippets/external-code-snippets.md
znai-docs/znai/visuals/images.md
znai-website-gen/src/main/java/org/testingisdocumenting/znai/website/WebSiteDocStructure.java
znai-website-gen/src/test/groovy/org/testingisdocumenting/znai/extensions/table/TableFencePluginTest.groovy

snippets,tables,images: auto anchorId from title

---

znai-docs/znai/visuals/cards.md
znai-reactjs/src/App.css
znai-reactjs/src/doc-elements/card/Card.css
znai-reactjs/src/doc-elements/card/Card.tsx
znai-reactjs/src/doc-elements/card/CardsDemo.tsx
znai-reactjs/src/doc-elements/card/cardContentAnalyzer.ts
znai-reactjs/src/doc-elements/demo-utils/contentGenerators.ts
znai-reactjs/src/theme/znai-dark/znai-dark.css

cards: link support

---

znai-core/src/main/java/org/testingisdocumenting/znai/extensions/features/PluginFeatureList.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/file/FileIncludePlugin.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/file/SnippetsCommon.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/file/SnippetsCommonFeatures.java
znai-docs/znai/release-notes/1.61/fix-2022-09-27-java-anchor-id.md
znai-docs/znai/snippets/external-code-snippets.md
znai-java/src/main/java/org/testingisdocumenting/znai/java/extensions/JavaDocIncludePlugin.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/extensions/JavaDocParamsIncludePlugin.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/extensions/JavaEnumEntriesIncludePlugin.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/extensions/JavaIncludePlugin.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/extensions/JavaIncludePluginBase.java

java: fix linking through anchorId

---

znai-core/src/main/java/org/testingisdocumenting/znai/parser/table/MarkupTableData.java
znai-core/src/main/java/org/testingisdocumenting/znai/parser/table/Row.java
znai-core/src/test/groovy/org/testingisdocumenting/znai/parser/table/MarkupTableDataTest.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/parser/table/RowTest.groovy
znai-docs/znai/layout/table/table.csv
znai-docs/znai/layout/tables.md
znai-docs/znai/lookup-paths
znai-docs/znai/release-notes/1.61/add-2022-09-28-table-filter-regexp.md
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/table/TableDocElementFromParams.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/table/TableFencePlugin.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/table/TableIncludePlugin.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/table/TablePluginParams.java

tables: filter rows by regexp

---

znai-docs/znai/layout/table-multiline.csv
znai-docs/znai/layout/tables.md
znai-docs/znai/release-notes/1.61/doc-2022-09-29-table-multiline.md

tables: doc multiline content

---

znai-core/src/main/java/org/testingisdocumenting/znai/structure/TableOfContents.java
znai-core/src/main/java/org/testingisdocumenting/znai/structure/TocItem.java
znai-core/src/test/groovy/org/testingisdocumenting/znai/extensions/toc/PageTocIncludePluginTest.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/structure/TableOfContentsTest.groovy
znai-docs/znai/release-notes/1.61/fix-2022-09-30-index-title.md
znai-reactjs/src/doc-elements/Documentation.js
znai-reactjs/src/doc-elements/page/PageTitle.js
znai-sphinx/src/main/java/org/testingisdocumenting/znai/parser/sphinx/DocTreeTocGenerator.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/website/WebSite.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/website/markups/MarkdownParsingConfiguration.java
znai-website-gen/src/test/groovy/org/testingisdocumenting/znai/website/WebSiteDocStructureTest.groovy

site: allow index title override

---

znai-docs/znai/release-notes/1.61.2/fix-2022-10-19-card-auxiliary-file.md
znai-docs/znai/release-notes/2022.md
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/card/CardFencePlugin.java

card: support additional images

---

znai-diagrams/src/test/groovy/org/testingisdocumenting/znai/diagrams/graphviz/GraphvizEngineTest.groovy
znai-diagrams/src/test/groovy/org/testingisdocumenting/znai/diagrams/graphviz/gen/GraphvizFromJsonGenTest.groovy
znai-docs/znai/release-notes/1.62/fix-2022-11-25-graphviz-multiline-fix.md
znai-utils/src/main/java/org/testingisdocumenting/znai/utils/RegexpUtils.java
znai-utils/src/test/groovy/org/testingisdocumenting/znai/utils/RegexpUtilsTest.groovy

flowdiagrams: fix multi line when color or shape is set

---

znai-docs/znai/release-notes/1.62/doc-2022-11-29-open-api-prop-title.md
znai-open-api/src/main/java/org/testingisdocumenting/znai/openapi/OpenApi3Schema.java
znai-open-api/src/test/groovy/org/testingisdocumenting/znai/openapi/OpenApi3SchemaToApiParametersConverterTest.groovy
znai-reactjs/src/doc-elements/api/ApiParameter.css
znai-reactjs/src/doc-elements/demo-utils/contentGenerators.ts

openapi: handle prop title

---

pom.xml
znai-core/src/main/java/org/testingisdocumenting/znai/parser/commonmark/MarkdownParser.java
znai-core/src/test/groovy/org/testingisdocumenting/znai/parser/TestComponentsRegistry.groovy
znai-core/src/test/groovy/org/testingisdocumenting/znai/parser/TestMarkdownParser.groovy
znai-docs/znai/java/HelloWorld.java
znai-docs/znai/java/HelloWorldMarkdown.java
znai-docs/znai/java/description-extraction.md
znai-docs/znai/release-notes/1.62/add-2022-12-01-javadoc-markdown.md
znai-java/src/main/java/org/testingisdocumenting/znai/java/extensions/JavaDocIncludePlugin.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/extensions/JavaDocMarkdownParameter.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/extensions/JavaDocParamsIncludePlugin.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/extensions/JavaEnumEntriesIncludePlugin.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/extensions/JavaIncludePluginBase.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/parser/JavaCodeVisitor.java
znai-java/src/main/java/org/testingisdocumenting/znai/java/parser/html/HtmlToDocElementConverter.java
znai-java/src/test/groovy/org/testingisdocumenting/znai/java/extensions/JavaDocIncludePluginTest.groovy
znai-java/src/test/groovy/org/testingisdocumenting/znai/java/extensions/JavaDocParamsIncludePluginTest.groovy
znai-java/src/test/groovy/org/testingisdocumenting/znai/java/extensions/JavaEnumEntriesIncludePluginTest.groovy
znai-java/src/test/groovy/org/testingisdocumenting/znai/java/parser/JavaCodeTest.groovy
znai-java/src/test/groovy/org/testingisdocumenting/znai/java/parser/html/HtmlToDocElementConverterTest.groovy
znai-java/src/test/resources/Enum.java
znai-java/src/test/resources/EnumMarkdown.java
znai-java/src/test/resources/WithJavaDocs.java
znai-jupyter/src/main/java/org/testingisdocumenting/znai/jupyter/JupyterIncludePlugin.java

java: markdown support in javadoc

---

znai-docs/znai/release-notes/1.63/add-2023-01-09-json-enclose-in-object.md
znai-docs/znai/snippets/json.md
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/json/JsonBasePlugin.java
znai-website-gen/src/test/groovy/org/testingisdocumenting/znai/extensions/json/JsonFencePluginTest.groovy

json: enclose in object

---

znai-core/src/main/java/org/testingisdocumenting/znai/extensions/file/SnippetCleaner.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/file/SnippetContainerEntriesConverter.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/file/SnippetHighlightFeature.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/file/SnippetRevealLineStopFeature.java
znai-core/src/test/groovy/org/testingisdocumenting/znai/extensions/file/SnippetCleanerTest.groovy
znai-docs/znai/release-notes/1.55/_fix-2021-12-24-ansi-background-fix.md
znai-docs/znai/release-notes/1.63/add-2023-01-02-trim-empty-lines-no-params.md
znai-docs/znai/release-notes/1.63/add-2023-01-10-cli-output-highlight-remove-ansi.md
znai-docs/znai/snippets/CLI.md
znai-docs/znai/snippets/cli/file-path-of-asserted-lines.txt

cli: output highlight matches sub-lines ignoring colors ANSI sequence

---

znai-docs/znai/release-notes/1.63/add-2023-01-16-openapi-summary-validation-auto-section.md
znai-open-api/src/main/java/org/testingisdocumenting/znai/openapi/OpenApi3IncludePlugin.java
znai-open-api/src/test/groovy/org/testingisdocumenting/znai/openapi/OpenApi3IncludePluginTest.groovy
znai-open-api/src/test/groovy/org/testingisdocumenting/znai/openapi/OpenApi3SpecTest.groovy
znai-open-api/src/test/resources/hello-app-spec2.json
znai-open-api/src/test/resources/test-openapi3.json

openapi: summary validation when autoSection: true

---

znai-open-api/src/test/groovy/org/testingisdocumenting/znai/openapi/OpenApi3SpecTest.groovy

openapi: basePath extra test

---

znai-core/src/main/java/org/testingisdocumenting/znai/extensions/PropsUtils.java
znai-core/src/test/groovy/org/testingisdocumenting/znai/extensions/json/JsonIncludePluginTest.groovy
znai-core/src/test/resources/with-null.json
znai-docs/znai/release-notes/1.63/fix-2023-02-06-json-null.md

json: fix null render

---

znai-core/src/main/java/org/testingisdocumenting/znai/extensions/PluginParamsDefinition.java
znai-docs/znai/layout/table/table-conflict.csv
znai-docs/znai/layout/tables.md
znai-docs/znai/release-notes/1.63/fix-2023-02-08-table-params-conflict.md
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/table/TableDocElementFromParams.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/table/TableIncludePlugin.java
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/table/TablePluginParams.java
znai-website-gen/src/test/groovy/org/testingisdocumenting/znai/extensions/table/TableIncludePluginTest.groovy
znai-website-gen/src/test/resources/test-table-title-column.json

table: fix column parameters name conflict

---

znai-core/src/main/java/org/testingisdocumenting/znai/extensions/json/JsonBasePlugin.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/json/JsonIncludePlugin.java
znai-core/src/main/java/org/testingisdocumenting/znai/extensions/validation/EntryPresenceValidation.java
znai-core/src/test/groovy/org/testingisdocumenting/znai/extensions/json/JsonIncludePluginTest.groovy
znai-docs/znai/release-notes/1.64/add-2023-07-02-json-callouts.md
znai-docs/znai/snippets/json.md
znai-reactjs/src/doc-elements/code-snippets/CodeSnippetWithCallouts.demo.tsx
znai-reactjs/src/doc-elements/code-snippets/CodeSnippetWithCallouts.tsx
znai-reactjs/src/doc-elements/code-snippets/Snippet.js
znai-reactjs/src/doc-elements/code-snippets/explanations/SnippetBulletExplanations.tsx
znai-reactjs/src/doc-elements/json/Json.demo.tsx
znai-reactjs/src/doc-elements/json/Json.js
znai-reactjs/src/doc-elements/json/jsonPrinter.ts

json: add callouts

---

znai-docs/znai/release-notes/1.64/fix-2023-09-04-links-from-index.md
znai-website-gen/src/main/java/org/testingisdocumenting/znai/website/WebSiteDocStructure.java
znai-website-gen/src/test/groovy/org/testingisdocumenting/znai/website/WebSiteDocStructureTest.groovy

fix: links from index page are no longer broken

---

pom.xml
znai-diagrams/pom.xml

diagrams: use plantuml-bsd

---

znai-charts/src/main/java/org/testingisdocumenting/znai/charts/ChartIncludeBasePlugin.java
znai-charts/src/main/java/org/testingisdocumenting/znai/charts/ChartPluginResult.java
znai-charts/src/test/groovy/org/testingisdocumenting/znai/charts/ChartPluginResultTest.groovy
znai-docs/znai/release-notes/1.66/add-2023-12-15-charts-columns.md
znai-docs/znai/visuals/charts.md

This allows to specify CSV files with more columns, in case you only want to display a few of them (or split them into several charts).

Add ability to filter by columns for charts

---

znai-docs/znai/doxygen/src/classes.h
znai-docs/znai/doxygen/xml/classes_8h.xml
znai-docs/znai/doxygen/xml/classutils_1_1second_1_1MyClass.xml
znai-docs/znai/doxygen/xml/classutils_1_1second_1_1ThirdClass.xml
znai-docs/znai/release-notes/1.68/add-2024-03-07-doxygen-note.md
znai-doxygen/src/main/java/org/testingisdocumenting/znai/doxygen/parser/DoxygenDescriptionParser.java
znai-doxygen/src/test/groovy/org/testingisdocumenting/znai/doxygen/parser/DoxygenDescriptionParserTest.groovy
znai-doxygen/src/test/resources/doxygen-description-with-note.xml

doxygen: display @note block

---

znai-docs/znai/release-notes/1.70/fix-2024-05-29-view-on-index.md
znai-docs/znai/release-notes/2024.md
znai-reactjs/src/doc-elements/page/PageTitle.js

flow: view on link fix for index page

---

znai-docs/znai/release-notes/1.71/add-2024-08-21-latex-inline-margin-tweaks.md
znai-reactjs/src/doc-elements/latex/Latex.css
znai-reactjs/src/doc-elements/latex/Latex.tsx

latex: remove horizontal margin for inline

---

znai-docs/znai/layout/tabs.md
znai-docs/znai/release-notes/1.71/add-2024-08-28-default-tabs.md
znai-reactjs/src/doc-elements/tabs/Tabs.js
znai-website-gen/src/main/java/org/testingisdocumenting/znai/extensions/tabs/TabsFencePlugin.java
znai-website-gen/src/test/groovy/org/testingisdocumenting/znai/extensions/tabs/TabsFencePluginTest.groovy

tabs: default tab to use param

---

pom.xml

- this edit got lost in this commit https://github.com/testingisdocumenting/znai/commit/c744ef1653f4469a9c342ec60b496301bc733038

use property frontend-maven-plugin.installDirectory
